import { Router } from 'express';
import { pool } from '../database.js';
import { asyncHandler } from '../lib/asyncHandler.js';
import { validateBody } from '../middleware/validate.js';
import { backupConfigBody } from '../validation/schemas.js';
import { runBackup } from '../services/backups.js';
import { rescheduleBackup } from '../services/backupScheduler.js';
import { writeFile } from 'fs/promises';
import { join } from 'path';

const router = Router();

// Get backup config for a stack
router.get('/:stackId/config', asyncHandler(async (req, res) => {
  const { rows: [config] } = await pool.query(
    'SELECT * FROM backup_configs WHERE stack_id = $1', [req.params.stackId]
  );
  if (!config) {
    res.json({
      enabled: false,
      cronSchedule: '0 22 * * 3',
      retentionDays: 7,
      includeStackFolder: true,
      includeVolumes: true,
      includeDatabases: false,
      useAdvancedRetention: false,
      retentionPolicy: {
        keepLast: 10,
        keepHourly: 24,
        keepDaily: 7,
        keepWeekly: 4,
        keepMonthly: 6,
        keepYearly: 2,
      },
    });
    return;
  }
  res.json(mapBackupConfig(config));
}));

// Update backup config
router.put('/:stackId/config', validateBody(backupConfigBody), asyncHandler(async (req, res) => {
  const b = req.body;
  const { rows: [existing] } = await pool.query(
    'SELECT * FROM backup_configs WHERE stack_id = $1', [req.params.stackId]
  );

  if (existing) {
    await pool.query(
      `UPDATE backup_configs SET
        enabled = $1, cron_schedule = $2, retention_days = $3,
        include_stack_folder = $4, include_volumes = $5, include_databases = $6,
        database_type = $7, database_config = $8, compression_level = $9,
        encrypted = $10, incremental = $11, use_advanced_retention = $12,
        retention_policy = $13, updated_at = NOW()
      WHERE stack_id = $14`,
      [
        b.enabled, b.cronSchedule || '0 22 * * 3', b.retentionDays || 7,
        b.includeStackFolder ?? true, b.includeVolumes ?? true, b.includeDatabases ?? false,
        b.databaseType || 'none', JSON.stringify(b.databaseConfig || {}), b.compressionLevel ?? 6,
        b.encrypted ?? false, b.incremental ?? false, b.useAdvancedRetention ?? false,
        JSON.stringify(b.retentionPolicy || {
          keepLast: 10,
          keepHourly: 24,
          keepDaily: 7,
          keepWeekly: 4,
          keepMonthly: 6,
          keepYearly: 2,
        }),
        req.params.stackId,
      ]
    );
  } else {
    await pool.query(
      `INSERT INTO backup_configs (stack_id, enabled, cron_schedule, retention_days,
        include_stack_folder, include_volumes, include_databases, database_type,
        database_config, compression_level, encrypted, incremental,
        use_advanced_retention, retention_policy)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)`,
      [
        req.params.stackId, b.enabled, b.cronSchedule || '0 22 * * 3', b.retentionDays || 7,
        b.includeStackFolder ?? true, b.includeVolumes ?? true, b.includeDatabases ?? false,
        b.databaseType || 'none', JSON.stringify(b.databaseConfig || {}), b.compressionLevel ?? 6,
        b.encrypted ?? false, b.incremental ?? false, b.useAdvancedRetention ?? false,
        JSON.stringify(b.retentionPolicy || {
          keepLast: 10,
          keepHourly: 24,
          keepDaily: 7,
          keepWeekly: 4,
          keepMonthly: 6,
          keepYearly: 2,
        }),
      ]
    );
  }

  // Reschedule
  rescheduleBackup({ stack_id: req.params.stackId, enabled: b.enabled, cron_schedule: b.cronSchedule });

  // Write backup.md to stack folder
  try {
    const { rows: [stack] } = await pool.query('SELECT * FROM stacks WHERE id = $1', [req.params.stackId]);
    if (stack?.stack_path) {
      const scheduleLabels: Record<string, string> = {
        '0 22 * * 3': 'Every Wednesday at 22:00',
        '0 22 * * 0': 'Every Sunday at 22:00',
        '0 22 1 * *': 'Every 1st of Month at 22:00',
      };
      const scheduleLabel = scheduleLabels[b.cronSchedule || ''] || b.cronSchedule || 'Not set';
      const retentionInfo = b.useAdvancedRetention
        ? `Advanced:\n  - Keep Last: ${b.retentionPolicy?.keepLast ?? 10}\n  - Keep Hourly: ${b.retentionPolicy?.keepHourly ?? 24}\n  - Keep Daily: ${b.retentionPolicy?.keepDaily ?? 7}\n  - Keep Weekly: ${b.retentionPolicy?.keepWeekly ?? 4}\n  - Keep Monthly: ${b.retentionPolicy?.keepMonthly ?? 6}\n  - Keep Yearly: ${b.retentionPolicy?.keepYearly ?? 2}`
        : `Simple: Keep last ${b.retentionDays ?? 7} backups`;

      const md = `# Backup Configuration: ${stack.name}

> Auto-generated by Homelab Commander. Edit this config via the UI — do not modify manually.

## Status

| Setting | Value |
|---------|-------|
| Enabled | ${b.enabled ? '✓ Yes' : '✗ No'} |
| Schedule | \`${b.cronSchedule || 'not set'}\` — ${scheduleLabel} |
| Retention | ${b.useAdvancedRetention ? 'Advanced (see below)' : `Keep last ${b.retentionDays ?? 7} backups`} |
| Compression | Level ${b.compressionLevel ?? 6} / 9 |
| Encrypted | ${b.encrypted ? '✓ Yes' : '✗ No'} |
| Incremental | ${b.incremental ? '✓ Yes' : '✗ No'} |

## Contents

- [${b.includeStackFolder !== false ? 'x' : ' '}] Full stack folder (everything except \`.git\`)
- [${b.includeVolumes !== false ? 'x' : ' '}] Docker volumes
- [${b.includeDatabases ? 'x' : ' '}] Database dumps${b.includeDatabases ? ` (${b.databaseType || 'postgres'})` : ''}

## Naming Convention

\`\`\`
{stackName}_stack_{YYYYMMDD-HHmmss}.tar.gz
{stackName}_vol-{volumeName}_{YYYYMMDD-HHmmss}.tar.gz
{stackName}_db-{dbName}_{YYYYMMDD-HHmmss}.sql.gz
\`\`\`

Example: \`${stack.name}_stack_${new Date().toISOString().slice(0, 10).replace(/-/g, '')}-070000.tar.gz\`

## Retention Policy

${retentionInfo}

*Last updated: ${new Date().toISOString()}*
`;
      await writeFile(join(stack.stack_path, 'backup.md'), md, 'utf8');
    }
  } catch { /* non-fatal — backup.md is a convenience file */ }

  res.json({ ok: true });
}));

// Get backup jobs for a stack
router.get('/:stackId/jobs', asyncHandler(async (req, res) => {
  const { rows } = await pool.query(
    'SELECT * FROM backup_jobs WHERE stack_id = $1 ORDER BY started_at DESC LIMIT 50',
    [req.params.stackId]
  );
  res.json(rows.map(mapBackupJob));
}));

// Run backup now
router.post('/:stackId/run', asyncHandler(async (req, res) => {
  const stackId = String(req.params.stackId);
  await runBackup(stackId);
  res.json({ ok: true });
}));

function mapBackupConfig(row: any) {
  return {
    enabled: row.enabled,
    cronSchedule: row.cron_schedule,
    retentionDays: row.retention_days,
    includeStackFolder: row.include_stack_folder,
    includeVolumes: row.include_volumes,
    includeDatabases: row.include_databases,
    databaseType: row.database_type,
    databaseConfig: row.database_config,
    compressionLevel: row.compression_level,
    encrypted: row.encrypted,
    incremental: row.incremental,
    useAdvancedRetention: row.use_advanced_retention,
    retentionPolicy: row.retention_policy,
  };
}

function mapBackupJob(row: any) {
  return {
    id: row.id,
    stackId: row.stack_id,
    status: row.status,
    sizeBytes: row.size_bytes,
    backupPath: row.backup_path,
    includes: row.includes,
    errorMessage: row.error_message,
    startedAt: row.started_at,
    completedAt: row.completed_at,
  };
}

export default router;
